### ISSUE TITLE
ERROR 404, page not found

### ISSUE THREAD

**Issue by cleitonpena** [erik78se/operator-gitlab-runner#12]
Hello:

This link
https://gitlab.com/gitlab-org/gitlab-runner/blob/master/docs/install/linux-repository.md

Return:

404
Page Not Found
Make sure the address is correct and the page hasn't moved.

Please contact your GitLab administrator if you think this is a mistake.

**Comment by erik78se** [comment]
Closing this issue since the fix is merged.
