### ISSUE TITLE
Template config flag provided but not defined.

### ISSUE THREAD

**Issue by giusebar** [erik78se/operator-gitlab-runner#13]
Hello,

I'm experiencing issues with registering runners through this charm. I'm currently deploying a GitLab Server via Juju on Focal.

I'm deploying the runner with the following command:

```
juju deploy gitlab-runner --config my-config.yaml --series focal
```

I'm getting the following error message:
```
WARNING unit.gitlab-runner-one-docker/0.config-changed logger.go:60 FATAL: flag provided but not defined: -template-config
```
From within the charm I can run the gitlab-runner register command successfully, however it seems that the charm version it is using the flag --template-config which is only available from runner v. 12.2. The latest gitlab-runner version in focal seems to be 11.2 (which is currently installed in my VM).
To confirm this, I've run the command to be registered with the above-mentioned flag and got the failure. 
I can see that flag being set [here](https://github.com/erik78se/operator-gitlab-runner/blob/main/gitlab-runner/src/gitlab_runner.py#L94), but the gitlab-runner version required to run that is not available on focal via apt as shown also [here](https://www.ubuntuupdates.org/package/core/focal/universe/base/gitlab-runner). 

Is there any way to address this issue?

Thanks in advance for the support,
Best,
Giuseppe

**Comment by erik78se** [comment]
Hello!

I wonder how you would get an "apt" version of gitlab installed since the charm installs from this: https://github.com/erik78se/operator-gitlab-runner/blob/main/gitlab-runner/src/charm.py#L73

E.g. it doesn't use the apt package manager to actually pull the runner in.

**Comment by giusebar** [comment]
Hello,
Thanks for your prompt reply!

That's a good point! The problem is that my machine is not able to access the https://packages.gitlab.com script and it installs the other package via the apt package manager. I will sort it out.

Thanks!
