### ISSUE TITLE
Gitlab runner doesnt honor concurent changes even with re-registration

### ISSUE THREAD

**Issue by itayo** [erik78se/operator-gitlab-runner#4]
when the charm is re-registered it doesn't change to the config value set in the charm config.

**Comment by erik78se** [comment]
I'm not able to reproduce this.

When I update the concurrent config - then run the action to unregister, then action register, the config seems to get the right new value. This works at least for docker, perhaps this is different for LXD?

**Comment by erik78se** [comment]
Indeed, this was a lxd registration issue.
