### ISSUE TITLE
Docker-in-Docker

### ISSUE THREAD

**Issue by FlashJonas** [erik78se/operator-gitlab-runner#8]
To be able to use docker-in-docker / "dind", you might need to mount `docker.sock` inside the container that is being run.
Currently there is no automated way of changing this, and you will have to ssh into the gitlab-runner and edit the config.toml file and add this under volume `var/run/docker.sock:/var/run/docker.sock`
Also, to be able to read and save reports as artifacts when using GitLab CodeQuality with CodeClimate, you might need to mount "/builds:/builds" as well. 
This leads to 1 or 2 feature requests:
- be able to add/configure volume mounts in the config.toml using JUJU
- configure for dind: get the automated docker.sock mount automatically

Thank you! :)

**Comment by erik78se** [comment]
It think adding to this file for the docker.sock would implement the second feature, right?

https://github.com/erik78se/operator-gitlab-runner/blob/main/gitlab-runner/templates/runner-templates/docker-1.template

**Comment by niklasmelin** [comment]
PR #17 : Adds support for Docker in Docker. If I have time I will look into fixing volumes as well.

**Comment by erik78se** [comment]
I have released a revision 8 to charmhub edge channel.

Revision 8 of charm 'gitlab-runner' released to edge

Thanx @niklasmelin !

If it seems to work for you guys, I'll merge it into the main branch.
