### ISSUE TITLE
first use failed, question on getting Docker to work

### ISSUE THREAD

**Issue by EMCP** [erik78se/operator-gitlab-runner#9]
hej Erik,

I am starting to trial the gitlab-runner charm.. but it seems I've hit the first snag.. I wanted to use Docker but am running within LXD.. can I use docker images within LXD or .. I guess whatever I need to setup to run should already be present in the same machine ?  If I just want to use docker images do I .. back the charm for k8s usage and spin it up on minik8s?

```
Running with gitlab-runner 14.9.1 ()
  on juju-1.lxd 
Preparing the "docker" executor
Using Docker executor with image registry.gitlab.com/jrgemcp-public/gitlab-cicd-docker/build-conan-docker:latest ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/jrgemcp-public/gitlab-cicd-docker/build-conan-docker:latest ...
Using docker image sha256:232827d262f12ccc14ba7d4fb14b611e80e57df059d61854366054cdd3ff9dc8 for registry.gitlab.com/jrgemcp-public/gitlab-cicd-docker/build-conan-docker:latest with digest registry.gitlab.com/jrgemcp-public/gitlab-cicd-docker/build-conan-docker@sha256:93fbdb226fa193b765ea350578850b8955a2dc6103ad8bb26c9c3294e5dd7078 ...
Preparing environment
Running on runner-concurrent-0 via juju-1...
Getting source from Git repository
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/some_project/.git/
Created fresh repository.
Checking out ffffff as main...
Skipping Git submodules setup
Executing "step_script" stage of the job script
Using docker image sha256:232827d262f12ccc14ba7d4fb14b611e80e57df059d61854366054cdd3ff9dc8 for registry.gitlab.com/jrgemcp-public/gitlab-cicd-docker/build-conan-docker:latest with digest registry.gitlab.com/jrgemcp-public/gitlab-cicd-docker/build-conan-docker@sha256:93fbdb226fa193b765ea350578850b8955a2dc6103ad8bb26c9c3294e5dd7078 ...
Cleaning up project directory and file based variables
ERROR: Job failed (system failure): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (docker.go:654:120s)
```

**Comment by EMCP** [comment]
hmmm thought I had this working but... had to manually install docker in the LXD based container.. then realized that that wasnt working either.. (just hangs when pulling first image)

if I use the LXD flag .. will all my jobs which use docker not run ? or .. does this require I setup LXD in a special way? Seeing posts about warnings running docker in LXD and trying to understand

https://stackoverflow.com/questions/51600186/gitlab-runner-docker-executor-in-lxd-container

https://ubuntu.com/tutorials/how-to-run-docker-inside-lxd-containers#1-overview

Regarding the config option
```
executor | string

Default: docker

"Can be: docker or lxd. Determines if this runner 
 uses a lxd or docker executor."
```

is it implied that this charm runs .. only on non-LXD clouds? thanks

**Comment by erik78se** [comment]
Hey Erik!

I'm not super accustomed to the lxd+docker setup. I'd love to get a PR from you about how it could be made to work for you as I'm really just developing this in the direction that people are actually using it.

If you like, I'll give you developer access to the repo....

Also, I'm keen no getting it to be properly working for DIND whith there is a Issue on aswell.

**Comment by EMCP** [comment]
my initial assessment is.. due to me using LXD and not say... EC2 or VMWare.. is even if you install docker on the same image (which this charm does not) .. it requires LXD to have some special setup which I had never done nor feel I have time right now to perform.. so the workaround for now was I just simply manually installed a runner on my Kubuntu 20.04 LTS manually.. and installed docker alongside that..

for the gitlab-runner to work well in Juju + LXD.. I imagine we'd have to do those instructions and that's probably not going to scale ..  leading me to wonder.. what happens if I chose the LXD executor?

Feels like this charm is only meant for certain clouds (due to the requirement that docker be setup and working).. maybe we can place a warning or codify it in the charm a bit better .. given the new `charmcraft`

Just to add , my experience with this charm in LXD was as follows

1) it defaults to docker.. but docker is not installed via the charm hooks
2) as a workaround I installed docker myself manually.. but then it just hung forever when attempting the `docker pull`

my conclusion is, docker inside LXD requires some special things so.. this default behavior is not recommended for LXD default storage pool (zfs)
